name: cltv_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.8
  - ipywidgets=7.5.0
  - numpy=1.16.2
  - matplotlib=2.2.2
  - pandas=0.24.2
  - pandas-gbq=0.6.0
  - pandoc=1.19.2.1
  - requests=2.20.0
  - seaborn=0.9.0
  - scikit-learn=0.21.2
  - scipy=1.1.0
  - shap=0.29.3
  - sqlalchemy=1.2.7
  - yaml=0.1.7
  - python-snappy==0.5.4
  - pillow==5.4.1
  - mysqlclient==1.3.14
  - xgboost=0.90
  - pip:
    - bz2file==0.98
    - cached-property==1.5.1
    - docopt==0.6.2
    - google-api-core==1.8.0
    - google-auth==1.5.0
    - google-cloud-bigquery==1.6.0
    - google-cloud-core==0.28.1
    - google-cloud-storage==1.10.0
    - gunicorn==19.9.0
    - jmespath==0.9.3
    - joblib==0.13.1
    - jupyter==1.0.0
    - msgpack==0.6.1
    - mysql-connector-python==8.0.15
    - pipreqs==0.4.9
    - psycopg2-binary==2.7.7
    - pulp==1.6.9
    - pyarrow==0.12.1
    - pyasn1==0.4.6
    - pymysql==0.9.2
    - pytest-runner==4.4
    - s3fs==0.2.0
    - sagemaker==1.43.2
    - smart-open==1.7.1
    - tables==3.4.3
    - texttable==0.9.1
    - thrift==0.11.0
    - timeutils==0.3.2
    - vadersentiment==3.2.1
    - virtualenv==16.3.0
    - virtualenvwrapper-win==1.2.5
    - websocket-client==0.55.0
    - yarg==0.1.9
