name: cltv_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6.8
  - ipywidgets=7.5.0
  - numpy=1.16.2
  - matplotlib=2.2.2
  - pandas=0.24.2
  - pandas-gbq=0.8.0
  - pandoc=1.19.2.1
  - pip=19.3.1
  - requests=2.20.0
  - seaborn=0.9.0
  - scikit-learn=0.21.2
  - scipy=1.1.0
  - shap=0.29.3
  - sqlalchemy=1.2.7
  - yaml=0.1.7
  - mysqlclient==1.3.14
  - xgboost=0.90
  - pip:
    - boto3==1.10.8
    - google-api-core==1.8.0
    - google-auth==1.5.0
    - google-cloud-bigquery==1.6.0
    - google-cloud-core==0.28.1
    - google-cloud-storage==1.10.0
    - hyperopt==0.2.2
    - joblib==0.13.1
    - jupyter==1.0.0
    - msgpack==0.6.1
    - mysql-connector-python==8.0.15
    - pymysql==0.9.2
    - sagemaker==1.43.2
    - timeutils==0.3.2
